#!/usr/bin/env bash

# Ensure CLI is installed
# shellcheck disable=SC2164
cd ./cli
if ! yarn check --integrity 2>/dev/null | grep -q 'success Folder in sync.'; then
    echo "Installing the cli...";
    yarn install;
    echo "";
fi
cd ../;

# Run eslint on the CLI code if requested
if [[ "${1}" = "eslint" ]]; then
    cd ./cli;
    NODE_OPTIONS="--trace-warnings" yarn lint --max-warnings=0;
    exit;
fi

# Run in dev mode if requested
if [[ "${1}" = "dev-mode" ]]; then
    # Send all arguments except the first one
    ./cli/bin/dev "${@:2}";
    exit;
fi

# Build new CLI if the cli/src directory has changed since last build
SRC_DIR_HASH_FILE=$(pwd)/cli/.src-dir-hash;
touch "${SRC_DIR_HASH_FILE}";
SRC_DIR_HASH_FILE_CONTENT=$(<"${SRC_DIR_HASH_FILE}");
SRC_DIR_HASH=$(find cli/src/ -type f -exec md5sum {} \; | md5sum);

if [[ "${SRC_DIR_HASH}" != "${SRC_DIR_HASH_FILE_CONTENT}" ]]; then
    cd ./cli;
    echo 'CLI source files have changed since last build. Building a fresh CLI now…';
    yarn build;
    echo "${SRC_DIR_HASH}" > "${SRC_DIR_HASH_FILE}";
    echo '';
    cd ../;
fi

# Otherwise, run the CLI
./cli/bin/run "${@}";
